### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by gboone** [18F/beta.18f.gov#25]
## Before Content Freeze (until August 31)
- [x] Figure out if we're OK with the lumpy font
- [x] Conduct manual accessibility review by @nickbristow (See #29) 
- [x] Get CircleCI set up to run [existing tests](https://github.com/18F/18f.gsa.gov/blob/staging/go#L115-L116) (See #28)
- [x] Review content (See ~~#35~~) — @awfrancisco 
- [ ] Draft blog posts about the redesign  https://github.com/18F/blog-drafts/issues/557
- [x] Move all blog posts into this repo (_Content freeze_)
- [x] Review blog post feature images and change to alternate blog image style when it doesn't look good (See #42)
- [x] Check formatting of posts with mixed markdown/html or special styles look OK. (See #54) Examples:
  - floating images: https://18f.gsa.gov/2015/04/08/day-in-the-life-of-talent-manager/, https://18f.gsa.gov/2015/03/12/day-in-the-life-of-an-18F-content-designer/
  - code blocks: https://18f.gsa.gov/2015/12/15/how-bot-named-dolores-landingham-transformed-18fs-onboarding/
- images and captions: https://18f.gsa.gov/2016/07/26/new-pilot-aims-to-streamline-notice-and-comment-process/
  - Long posts like these: https://18f.gsa.gov/tags/second-anniversary/
  - Embedded content:
    - YouTube: https://18f.gsa.gov/2016/03/24/video-highlights-from-18f-speeches-over-the-last-year/
    - Instagram: https://18f.gsa.gov/2016/01/21/what-we-can-learn-from-the-interiors-social-feeds/

**Test on all browsers** 
- [x] Latest Chrome
- [x] Firefox
- [x] Safari
- [x] IE 10+ 
- [x] Edge
- [x] Linux — ask @msecret or @konklone to review. Also, @gboone has a VM that he can test on.
- [x] Find five people to click on all the things
- [x] Fix anything that's _broken_
### Head's up to GSA
- [x] OCIA
- [x] OCM
- [x] OGC
- [x] Administrator's office, GSA senior leadership
- [x] **Code freeze (Aug. 29)** 
## Soft launch and content freeze (Sept. 1-2)
- [x] ~~Set up archive.18f.gov as a failsafe. All blog posts published to both 18f.gsa.gov and archive.18f.gov~~
- [x] Optimize and bring all images into this repo
- [x] Close or merge all open PRs
- [x] Close any obsolete issues
- [x] Delete all old branches including `production`
- [ ] Eliminate old versions of images from Git history to prevent the repo from becoming enormous
- [x] ~~Rename 18F/18f.gsa.gov to 18F/legacy-18f-site~~
- [x] Put a disclaimer on beta.18f.gov and notice in the README of this repo explaining where to find Git history and the code powering the site.
- [x] Switch Federalist and GitHub main branches to `master`
## Launch (Sept. 6)
- [x] GSA blog post (Likely not happening)
- [ ] 18F blog post (Doesn't have to happen, and likely won't, until after 9/6)
## Post-launch
- [ ] Design review
- [ ] Automatically rotate the hero image every few weeks
- [ ] Ensure formatting of posts published in the last few months all look OK after migration
- [ ] Integrate automated a11y scan into Circle CI (See #28)

**Comment by maya** [comment]
@gboone code blocks are already formatted: http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18F/beta.18f.gov/2016/06/24/5-lessons-in-object-oriented-design-from-sandi-metz/ although no syntax highlighting implemented yet.

**Comment by quepol** [comment]
Need to make a list of who needs to approve. At first blush:
- [ ] hillary, aaron, heads up to shive
- [ ] OCM (Brett, unless he delegates, Ashley)
- [ ] OGC (if flagged by OCM)
- [ ] Denise + Adam

**Comment by awfrancisco** [comment]
Issue filed for redesign launch post https://github.com/18F/blog-drafts/issues/557

**Comment by gboone** [comment]
@maya that's interesting, I thought syntax highlighting was all done automatically with `rouge` is there something in the WDS that would override that somehow? If not, I'll try and make sure rouge is functioning correctly.

**Comment by maya** [comment]
@gboone rouge is functioning but there aren't any styles added.

**Comment by maya** [comment]
Timeline:
- **8/23** — Get 5 people to review site
- **8/26** — Code freeze
- **9/1** — Soft launch
- **9/6** — Launch
